// Starter kits (2.58): every file in kits/ becomes one entry of src/features/store/kits.generated.ts, so adding a kit is
// adding a JSON file — no code. Runs before every build (npm "prebuild"); tests/store-kits.test.ts fails when the
// generated file and the folder differ ("npm run kits" fixes it). The kit itself is checked by validateKit (kits.ts).
// 2.63 (variants): the kit's design defaults — its header, footer, cards, spacing, buttons and each section's layout —
// are also written for the storefront (storefront/src/lib/kit-designs.json), which never imports the dashboard. The
// storefront checks every value against its own lists (lib/variants.ts), so this copy is data only.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
function kitFiles() {
  const files = readdirSync(`${root}kits`).filter((f) => f.endsWith('.json')).sort();
  return files.map((f) => {
    try { return JSON.parse(readFileSync(`${root}kits/${f}`, 'utf8')); }
    catch (e) { throw new Error(`kits/${f}: not valid JSON — ${e.message}`); }
  });
}
// 2.71: every function takes the kits (default: the folder's), so a test can add a kit without writing a file
export function generated(kits = kitFiles()) {
  return '// Generated by scripts/kits.mjs from kits/*.json — do not edit by hand ("npm run kits").\n'
    + `export const KIT_FILES: readonly unknown[] = ${JSON.stringify(kits, null, 2)};\n`;
}
const o = (v) => (v && typeof v === 'object' && !Array.isArray(v) ? v : {});
/** each kit's design defaults, as the storefront reads them */
export function storefrontDesigns(kits = kitFiles()) {
  const out = {};
  for (const k of kits) {
    const t = o(k.theme), ch = o(t.chrome), cd = o(t.commerceDesign);
    const sections = {};
    for (const s of Array.isArray(t.sections) ? t.sections : []) if (s && typeof s.id === 'string' && typeof s.variant === 'string') sections[s.id] = s.variant;
    out[k.id] = {
      design: { ...o(t.design) },
      chrome: { ...(ch.headerVariant ? { header: ch.headerVariant } : {}), ...(ch.footerVariant ? { footer: ch.footerVariant } : {}) },
      commerce: {
        ...(cd.productCardVariant ? { productCard: cd.productCardVariant } : {}),
        ...(cd.collectionCardVariant ? { collectionCard: cd.collectionCardVariant } : {}),
        ...(cd.productPageVariant ? { productPage: cd.productPageVariant } : {}),
      },
      sections,
    };
  }
  return `${JSON.stringify(out, null, 2)}\n`;
}
export const STOREFRONT_DESIGNS = `${root}../storefront/src/lib/kit-designs.json`;
/**
 * 2.63 (PR-2, a kit's preview without a write): each kit's own theme — its colours, font and home page with their texts —
 * as the storefront needs it to show a store in a kit it has not applied ("{{name}}" stays: the storefront fills it in).
 */
export function storefrontThemes(kits = kitFiles()) {
  const out = {};
  for (const k of kits) {
    const t = o(k.theme);
    out[k.id] = {
      name: k.name,
      theme: {
        colors: t.colors, font: t.font, art: t.art, radius: t.radius, announcement: t.announcement, product: t.product,
        sections: (Array.isArray(t.sections) ? t.sections : []).map((s) => ({ id: s.id, type: s.type, hidden: s.hidden === true, settings: s.settings })),
      },
    };
  }
  return `${JSON.stringify(out, null, 2)}\n`;
}
export const STOREFRONT_THEMES = `${root}../storefront/src/lib/kit-themes.json`;
/**
 * 2.71: the kits' picture manifests in one file for the storefront (storefront/src/lib/kit-images/<kit>.json are written by
 * scripts/kit-images.mjs, one per kit) — so a new kit's pictures are a manifest and its files, never an import in code.
 */
const MANIFEST_DIR = `${root}../storefront/src/lib/kit-images`;
export function manifestFiles() {
  return Object.fromEntries(readdirSync(MANIFEST_DIR).filter((f) => f.endsWith('.json')).sort()
    .map((f) => { const m = JSON.parse(readFileSync(`${MANIFEST_DIR}/${f}`, 'utf8')); return [m.kit, m]; }));
}
export const storefrontManifests = (manifests = manifestFiles()) => `${JSON.stringify(manifests, null, 2)}\n`;
export const STOREFRONT_MANIFESTS = `${root}../storefront/src/lib/kit-manifests.json`;
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(`${root}src/features/store/kits.generated.ts`, generated());
  writeFileSync(STOREFRONT_DESIGNS, storefrontDesigns());
  writeFileSync(STOREFRONT_THEMES, storefrontThemes());
  writeFileSync(STOREFRONT_MANIFESTS, storefrontManifests());
  console.log('kits: src/features/store/kits.generated.ts, storefront/src/lib/kit-designs.json, kit-themes.json and kit-manifests.json written');
}
