// Starter kits (2.58): every file in kits/ becomes one entry of src/features/store/kits.generated.ts, so adding a kit is
// adding a JSON file — no code. Runs before every build (npm "prebuild"); tests/store-kits.test.ts fails when the
// generated file and the folder differ ("npm run kits" fixes it). The kit itself is checked by validateKit (kits.ts).
// 2.63 (variants): the kit's design defaults — its header, footer, cards, spacing, buttons and each section's layout —
// are also written for the storefront (storefront/src/lib/kit-designs.json), which never imports the dashboard. The
// storefront checks every value against its own lists (lib/variants.ts), so this copy is data only.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
function kitFiles() {
  const files = readdirSync(`${root}kits`).filter((f) => f.endsWith('.json')).sort();
  return files.map((f) => {
    try { return JSON.parse(readFileSync(`${root}kits/${f}`, 'utf8')); }
    catch (e) { throw new Error(`kits/${f}: not valid JSON — ${e.message}`); }
  });
}
export function generated() {
  return '// Generated by scripts/kits.mjs from kits/*.json — do not edit by hand ("npm run kits").\n'
    + `export const KIT_FILES: readonly unknown[] = ${JSON.stringify(kitFiles(), null, 2)};\n`;
}
const o = (v) => (v && typeof v === 'object' && !Array.isArray(v) ? v : {});
/** each kit's design defaults, as the storefront reads them */
export function storefrontDesigns() {
  const out = {};
  for (const k of kitFiles()) {
    const t = o(k.theme), ch = o(t.chrome), cd = o(t.commerceDesign);
    const sections = {};
    for (const s of Array.isArray(t.sections) ? t.sections : []) if (s && typeof s.id === 'string' && typeof s.variant === 'string') sections[s.id] = s.variant;
    out[k.id] = {
      design: { ...o(t.design) },
      chrome: { ...(ch.headerVariant ? { header: ch.headerVariant } : {}), ...(ch.footerVariant ? { footer: ch.footerVariant } : {}) },
      commerce: {
        ...(cd.productCardVariant ? { productCard: cd.productCardVariant } : {}),
        ...(cd.collectionCardVariant ? { collectionCard: cd.collectionCardVariant } : {}),
        ...(cd.productPageVariant ? { productPage: cd.productPageVariant } : {}),
      },
      sections,
    };
  }
  return `${JSON.stringify(out, null, 2)}\n`;
}
export const STOREFRONT_DESIGNS = `${root}../storefront/src/lib/kit-designs.json`;
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(`${root}src/features/store/kits.generated.ts`, generated());
  writeFileSync(STOREFRONT_DESIGNS, storefrontDesigns());
  console.log('kits: src/features/store/kits.generated.ts and storefront/src/lib/kit-designs.json written');
}
