// Starter kits (2.58): every file in kits/ becomes one entry of src/features/store/kits.generated.ts, so adding a kit is
// adding a JSON file — no code. Runs before every build (npm "prebuild"); tests/store-kits.test.ts fails when the
// generated file and the folder differ ("npm run kits" fixes it). The kit itself is checked by validateKit (kits.ts).
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
export function generated() {
  const files = readdirSync(`${root}kits`).filter((f) => f.endsWith('.json')).sort();
  const kits = files.map((f) => {
    try { return JSON.parse(readFileSync(`${root}kits/${f}`, 'utf8')); }
    catch (e) { throw new Error(`kits/${f}: not valid JSON — ${e.message}`); }
  });
  return '// Generated by scripts/kits.mjs from kits/*.json — do not edit by hand ("npm run kits").\n'
    + `export const KIT_FILES: readonly unknown[] = ${JSON.stringify(kits, null, 2)};\n`;
}
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(`${root}src/features/store/kits.generated.ts`, generated());
  console.log('kits: src/features/store/kits.generated.ts written');
}
