// Generated by scripts/kits.mjs from kits/*.json — do not edit by hand ("npm run kits").
export const KIT_FILES: readonly unknown[] = [
  {
    "id": "bags",
    "name": "שקיות ממותגות",
    "description": "לעסקים שמוכרים שקיות ואריזות בהדפסה: סוגי שקיות, איך מזמינים, והדפסת לוגו.",
    "order": 10,
    "keywords": [
      "שקיות",
      "שקית",
      "אריזות",
      "אריזה",
      "מיתוג",
      "הדפסה על",
      "packaging",
      "bags"
    ],
    "seoDescription": "{{name}} — שקיות ממותגות לעסקים, בהדפסה לפי המידה שלכם.",
    "theme": {
      "colors": {
        "background": "#fbf8f3",
        "surface": "#ffffff",
        "text": "#1f1b16",
        "muted": "#5f574e",
        "primary": "#1f1b16",
        "accent": "#8a5a2b",
        "accentSoft": "#f1e6d6",
        "border": "#e7ddcf"
      },
      "font": "heebo",
      "art": "bag",
      "radius": "medium",
      "announcement": {
        "enabled": true,
        "text": "שקיות ממותגות לעסקים — עם הלוגו שלכם",
        "href": "/collections/all"
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "שקיות ממותגות",
            "title": "הלוגו שלכם, על כל שקית",
            "subtitle": "שקיות לעסקים בהדפסה לפי המידה שלכם. בוחרים דגם, שולחים לוגו — ומקבלים שקיות מוכנות.",
            "primaryLabel": "לכל השקיות",
            "primaryHref": "/collections/all",
            "secondaryLabel": "שאלה בוואטסאפ",
            "secondaryHref": "whatsapp",
            "image": ""
          }
        },
        {
          "id": "collections",
          "type": "collections",
          "hidden": false,
          "settings": {
            "title": "סוגי שקיות",
            "subtitle": ""
          }
        },
        {
          "id": "featured",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "הכי מבוקשות",
            "collection": "",
            "limit": 8,
            "buttonLabel": "לכל השקיות"
          }
        },
        {
          "id": "about",
          "type": "imageText",
          "hidden": false,
          "settings": {
            "title": "למה שקית ממותגת?",
            "text": "שקית עם הלוגו ממשיכה ללכת עם הלקוח גם אחרי הקנייה. היא חלק מהחוויה, והיא מזכירה את העסק בכל מקום שהיא מגיעה אליו.",
            "image": "",
            "buttonLabel": "איך מזמינים",
            "buttonHref": "/pages/how-to-order",
            "imageSide": "start"
          }
        },
        {
          "id": "steps",
          "type": "steps",
          "hidden": false,
          "settings": {
            "title": "איך זה עובד",
            "items": [
              {
                "title": "בוחרים שקית",
                "text": "דגם, מידה וצבע מהקטלוג."
              },
              {
                "title": "שולחים לוגו",
                "text": "קובץ של הלוגו, ואם יש — גם הנחיות להדפסה."
              },
              {
                "title": "מאשרים",
                "text": "מקבלים את כל הפרטים ומאשרים לפני ההדפסה."
              },
              {
                "title": "מקבלים",
                "text": "השקיות מגיעות מודפסות ומוכנות."
              }
            ]
          }
        },
        {
          "id": "faq",
          "type": "faq",
          "hidden": false,
          "settings": {
            "title": "שאלות נפוצות",
            "items": [
              {
                "q": "מה הכמות המינימלית להזמנה?",
                "a": "זה תלוי בדגם ובסוג ההדפסה. כתבו לנו מה אתם צריכים ונחזור עם הפרטים."
              },
              {
                "q": "באיזה קובץ לשלוח את הלוגו?",
                "a": "הכי טוב קובץ וקטורי (PDF, AI או SVG). אם אין — שלחו מה שיש ונבדוק יחד."
              }
            ]
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "נדבר?",
            "text": "שאלה על דגם, כמויות או הדפסה — כתבו לנו ונחזור אליכם."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "כל השקיות",
          "href": "/collections/all"
        },
        {
          "label": "שקיות נייר",
          "href": "/collections/paper"
        },
        {
          "label": "שקיות בד",
          "href": "/collections/fabric"
        },
        {
          "label": "איך מזמינים",
          "href": "/pages/how-to-order"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "הדפסה ולוגו",
          "href": "/pages/printing"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "משלוחים",
          "href": "/policies/shipping"
        },
        {
          "label": "תנאי שימוש",
          "href": "/policies/terms"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "paper",
        "title": "שקיות נייר",
        "description": "שקיות נייר עם הדפסה.",
        "tags": [
          "נייר"
        ]
      },
      {
        "slug": "fabric",
        "title": "שקיות בד",
        "description": "שקיות בד לשימוש חוזר.",
        "tags": [
          "בד"
        ]
      },
      {
        "slug": "gift",
        "title": "אריזות מתנה",
        "description": "אריזות ושקיות למתנות.",
        "tags": [
          "מתנה"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## מי אנחנו\n\n{{name}} מייצרים שקיות ממותגות לעסקים. [כמה מילים על העסק: ממתי, למי, ומה מיוחד אצלכם.]"
      },
      {
        "slug": "how-to-order",
        "title": "איך מזמינים",
        "body": "## ארבעה שלבים\n\n- בוחרים דגם, מידה וצבע מהקטלוג.\n- שולחים קובץ של הלוגו.\n- מקבלים את כל הפרטים ומאשרים לפני ההדפסה.\n- השקיות מגיעות מודפסות ומוכנות.\n\n## זמני הכנה\n\n[כמה זמן לוקחת הזמנה, מהאישור ועד שהשקיות אצלכם.]"
      },
      {
        "slug": "printing",
        "title": "הדפסה ולוגו",
        "body": "## איזה קובץ לשלוח\n\nהכי טוב קובץ וקטורי: PDF, AI או SVG. אם אין — שלחו מה שיש ונבדוק יחד.\n\n## צבעים ושיטות הדפסה\n\n[אילו שיטות הדפסה יש, וכמה צבעים אפשר להדפיס.]"
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## נשמח לשמוע מכם\n\nשאלה על דגם, כמויות או הדפסה — כתבו לנו בוואטסאפ, התקשרו או שלחו מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר."
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## מה הכמות המינימלית?\n\n[הכמות המינימלית לכל דגם.]\n\n## באיזה קובץ לשלוח את הלוגו?\n\nהכי טוב קובץ וקטורי (PDF, AI או SVG).\n\n## מתי ההזמנה מגיעה?\n\n[זמני הכנה ומשלוח.]"
      }
    ],
    "policies": {}
  },
  {
    "id": "beauty",
    "name": "ביוטי וקליניקה",
    "description": "לקליניקה, לסלון ולמכון: הטיפולים, לפני ואחרי, קביעת תור ומוצרי טיפוח.",
    "order": 40,
    "keywords": [
      "קליניקה",
      "ביוטי",
      "יופי",
      "קוסמטיקה",
      "קוסמטיקאית",
      "טיפוח",
      "טיפולי",
      "לייזר",
      "גבות",
      "ריסים",
      "ציפורניים",
      "מניקור",
      "מספרה",
      "איפור",
      "ספא",
      "beauty",
      "clinic",
      "salon",
      "spa"
    ],
    "seoDescription": "{{name}} — טיפולים, לפני ואחרי, קביעת תור ומוצרי טיפוח.",
    "theme": {
      "colors": {
        "background": "#fdf9f8",
        "surface": "#ffffff",
        "text": "#2a2224",
        "muted": "#6b5b5f",
        "primary": "#2a2224",
        "accent": "#9c5f6b",
        "accentSoft": "#f6e9eb",
        "border": "#eedfe1"
      },
      "font": "frank",
      "art": "plain",
      "radius": "large",
      "announcement": {
        "enabled": true,
        "text": "קובעים תור אונליין — בכמה לחיצות",
        "href": "booking"
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "{{name}}",
            "title": "הזמן שלך לטפח את עצמך",
            "subtitle": "טיפולים מקצועיים באווירה נעימה. בוחרים טיפול, קובעים תור — ואנחנו כבר מחכים.",
            "primaryLabel": "לקביעת תור",
            "primaryHref": "booking",
            "secondaryLabel": "שאלה בוואטסאפ",
            "secondaryHref": "whatsapp",
            "image": ""
          }
        },
        {
          "id": "treatments",
          "type": "imageText",
          "hidden": false,
          "settings": {
            "title": "הטיפולים שלנו",
            "text": "כאן כותבים על הטיפולים: מה עושים, למי זה מתאים, וכמה זמן לוקח כל טיפול.",
            "image": "",
            "buttonLabel": "לכל הטיפולים",
            "buttonHref": "/pages/treatments",
            "imageSide": "start"
          }
        },
        {
          "id": "before-after",
          "type": "gallery",
          "hidden": false,
          "settings": {
            "title": "לפני ואחרי",
            "text": "תוצאות אמיתיות של לקוחות שלנו, שפורסמו באישורן.",
            "items": [],
            "buttonLabel": "לקביעת תור",
            "buttonHref": "booking"
          }
        },
        {
          "id": "care",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "מוצרי טיפוח",
            "collection": "care",
            "limit": 4,
            "buttonLabel": "לכל המוצרים"
          }
        },
        {
          "id": "steps",
          "type": "steps",
          "hidden": false,
          "settings": {
            "title": "איך מגיעים לטיפול",
            "items": [
              {
                "title": "בוחרים טיפול",
                "text": "מתוך רשימת הטיפולים."
              },
              {
                "title": "קובעים תור",
                "text": "ביומן באתר, או בוואטסאפ."
              },
              {
                "title": "מגיעים",
                "text": "ואנחנו כבר מחכים לך."
              }
            ]
          }
        },
        {
          "id": "faq",
          "type": "faq",
          "hidden": false,
          "settings": {
            "title": "שאלות נפוצות",
            "items": [
              {
                "q": "כמה זמן לוקח טיפול?",
                "a": "זה תלוי בטיפול. בעמוד הטיפולים כתוב כמה זמן לוקח כל אחד."
              },
              {
                "q": "אפשר לבטל או להזיז תור?",
                "a": "כן — כתבו לנו מראש ונתאם מועד אחר."
              }
            ]
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "נשמח לראות אותך",
            "text": "שאלה על טיפול או על תור — כתבי לנו ונחזור אלייך."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "הטיפולים",
          "href": "/pages/treatments"
        },
        {
          "label": "לפני ואחרי",
          "href": "/#before-after"
        },
        {
          "label": "קביעת תור",
          "href": "booking"
        },
        {
          "label": "מוצרי טיפוח",
          "href": "/collections/care"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "הטיפולים",
          "href": "/pages/treatments"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "care",
        "title": "מוצרי טיפוח",
        "description": "מוצרים להמשך הטיפוח בבית.",
        "tags": [
          "טיפוח"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## נעים להכיר\n\n[מי מטפלת, מה הניסיון וההכשרה, ומה חשוב לכם בטיפול.]"
      },
      {
        "slug": "treatments",
        "title": "הטיפולים שלנו",
        "body": "## [שם הטיפול]\n\n[מה עושים בטיפול, למי הוא מתאים וכמה זמן הוא לוקח.]\n\n## [שם הטיפול]\n\n[מה עושים בטיפול, למי הוא מתאים וכמה זמן הוא לוקח.]\n\n## לפני הטיפול\n\n[הנחיות לפני ההגעה, אם יש.]"
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## נשמח לשמוע ממך\n\nשאלה על טיפול או על תור — כתבי לנו בוואטסאפ, התקשרי או שלחי מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר.\n\n## שעות הקבלה\n\n[ימים ושעות]"
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## כמה זמן לוקח טיפול?\n\n[משך כל טיפול.]\n\n## אפשר לבטל או להזיז תור?\n\n[עד מתי אפשר לבטל, ואיך.]"
      }
    ],
    "policies": {
      "returns": {
        "append": "## ביטול תור\n\n[עד מתי אפשר לבטל או להזיז תור, ומה קורה בביטול מאוחר.]"
      }
    }
  },
  {
    "id": "fashion",
    "name": "אופנה",
    "description": "לחנות בגדים ואקססוריז: חדש, נשים, גברים, מבצעים, טבלת מידות ואינסטגרם.",
    "order": 20,
    "keywords": [
      "בגדים",
      "ביגוד",
      "אופנה",
      "הלבשה",
      "שמלות",
      "חולצות",
      "נעליים",
      "תכשיטים",
      "אקססוריז",
      "בוטיק",
      "fashion",
      "clothing",
      "apparel"
    ],
    "seoDescription": "{{name}} — אופנה לנשים ולגברים, עם קולקציות חדשות ומבצעים.",
    "theme": {
      "colors": {
        "background": "#ffffff",
        "surface": "#ffffff",
        "text": "#111111",
        "muted": "#5c5c5c",
        "primary": "#111111",
        "accent": "#b0413e",
        "accentSoft": "#f6eeee",
        "border": "#e6e6e6"
      },
      "font": "assistant",
      "art": "plain",
      "radius": "small",
      "announcement": {
        "enabled": true,
        "text": "הקולקציה החדשה כבר באתר",
        "href": "/collections/new"
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "קולקציה חדשה",
            "title": "הלוק הבא שלכם מתחיל כאן",
            "subtitle": "פריטים חדשים, קלאסיקות שתמיד עובדות ואקססוריז שמשלימים את הלוק.",
            "primaryLabel": "לחדשים",
            "primaryHref": "/collections/new",
            "secondaryLabel": "למבצעים",
            "secondaryHref": "/collections/sale",
            "image": ""
          }
        },
        {
          "id": "new",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "חדש באתר",
            "collection": "new",
            "limit": 8,
            "buttonLabel": "לכל החדשים"
          }
        },
        {
          "id": "categories",
          "type": "collections",
          "hidden": false,
          "settings": {
            "title": "קנו לפי קטגוריה",
            "subtitle": ""
          }
        },
        {
          "id": "story",
          "type": "imageText",
          "hidden": false,
          "settings": {
            "title": "הסטייל שלנו",
            "text": "כאן מספרים על הסגנון של החנות: מה אתם אוהבים, איך אתם בוחרים את הפריטים ולמי הם מתאימים.",
            "image": "",
            "buttonLabel": "עוד עלינו",
            "buttonHref": "/pages/about",
            "imageSide": "end"
          }
        },
        {
          "id": "instagram",
          "type": "gallery",
          "hidden": false,
          "settings": {
            "title": "עקבו אחרינו באינסטגרם",
            "text": "השראה, לוקים ופריטים חדשים — קודם באינסטגרם.",
            "items": [],
            "buttonLabel": "לאינסטגרם שלנו",
            "buttonHref": ""
          }
        },
        {
          "id": "newsletter",
          "type": "newsletter",
          "hidden": true,
          "settings": {
            "title": "הראשונים לדעת",
            "text": "קולקציות חדשות ומבצעים — ישר למייל."
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "צריכים עזרה במידה?",
            "text": "כתבו לנו לפני שאתם מזמינים — נשמח לעזור לבחור."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "חדש",
          "href": "/collections/new"
        },
        {
          "label": "נשים",
          "href": "/collections/women"
        },
        {
          "label": "גברים",
          "href": "/collections/men"
        },
        {
          "label": "אקססוריז",
          "href": "/collections/accessories"
        },
        {
          "label": "מבצעים",
          "href": "/collections/sale"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "טבלת מידות",
          "href": "/pages/size-guide"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "משלוחים",
          "href": "/policies/shipping"
        },
        {
          "label": "החזרות והחלפות",
          "href": "/policies/returns"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "new",
        "title": "חדש",
        "description": "הפריטים החדשים באתר.",
        "tags": [
          "חדש"
        ]
      },
      {
        "slug": "women",
        "title": "נשים",
        "description": "בגדים ופריטים לנשים.",
        "tags": [
          "נשים"
        ]
      },
      {
        "slug": "men",
        "title": "גברים",
        "description": "בגדים ופריטים לגברים.",
        "tags": [
          "גברים"
        ]
      },
      {
        "slug": "accessories",
        "title": "אקססוריז",
        "description": "תיקים, תכשיטים ועוד.",
        "tags": [
          "אקססוריז"
        ]
      },
      {
        "slug": "sale",
        "title": "מבצעים",
        "description": "פריטים במבצע.",
        "tags": [
          "מבצע"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## הסיפור שלנו\n\n[איך {{name}} התחילה, ומה הסגנון שלכם.]\n\n## איך אנחנו בוחרים פריטים\n\n[מאיפה הבגדים, ומה חשוב לכם בבחירה.]"
      },
      {
        "slug": "size-guide",
        "title": "טבלת מידות",
        "body": "## איך מודדים\n\n- חזה: סביב החלק הרחב של החזה.\n- מותניים: סביב החלק הצר של הגוף.\n- ירכיים: סביב החלק הרחב של הירכיים.\n\n## המידות שלנו\n\n- S: [חזה / מותניים / ירכיים בס\"מ]\n- M: [חזה / מותניים / ירכיים בס\"מ]\n- L: [חזה / מותניים / ירכיים בס\"מ]\n- XL: [חזה / מותניים / ירכיים בס\"מ]\n\nלא בטוחים במידה? כתבו לנו לפני שאתם מזמינים."
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## נשמח לעזור\n\nשאלה על מידה, על פריט או על הזמנה — כתבו לנו בוואטסאפ, התקשרו או שלחו מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר."
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## איך יודעים איזו מידה להזמין?\n\nבעמוד טבלת המידות יש הסבר איך מודדים. לא בטוחים — כתבו לנו.\n\n## אפשר להחליף מידה?\n\n[מדיניות ההחלפות — ראו גם את עמוד ההחזרות.]\n\n## מתי ההזמנה מגיעה?\n\n[זמני אספקה.]"
      }
    ],
    "policies": {
      "returns": {
        "append": "## החלפת מידה\n\n[האם ואיך מחליפים מידה, ובאיזה מצב הפריט צריך להיות.]"
      }
    }
  },
  {
    "id": "furniture",
    "name": "רהיטים ובית",
    "description": "לחנות רהיטים ועיצוב הבית: סלון, חדר שינה, פינת אוכל, משרד ותאורה, עם עמוד משלוח והרכבה.",
    "order": 30,
    "keywords": [
      "רהיטים",
      "ריהוט",
      "רהיט",
      "עיצוב הבית",
      "לבית",
      "מטבחים",
      "תאורה",
      "נגרות",
      "ספות",
      "מזרנים",
      "furniture",
      "home decor"
    ],
    "seoDescription": "{{name}} — רהיטים ועיצוב לבית: סלון, חדר שינה, פינת אוכל, משרד ותאורה.",
    "theme": {
      "colors": {
        "background": "#f7f4ef",
        "surface": "#ffffff",
        "text": "#2b2622",
        "muted": "#625a52",
        "primary": "#2b2622",
        "accent": "#5f7353",
        "accentSoft": "#e9ede4",
        "border": "#e3ddd3"
      },
      "font": "rubik",
      "art": "plain",
      "radius": "small",
      "announcement": {
        "enabled": true,
        "text": "משלוח והרכבה — כל הפרטים באתר",
        "href": "/pages/delivery-assembly"
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "רהיטים ועיצוב לבית",
            "title": "בית שנעים לחזור אליו",
            "subtitle": "רהיטים לסלון, לחדר השינה, לפינת האוכל ולמשרד — ותאורה שמשלימה את הכל.",
            "primaryLabel": "לכל הרהיטים",
            "primaryHref": "/collections/all",
            "secondaryLabel": "ייעוץ בוואטסאפ",
            "secondaryHref": "whatsapp",
            "image": ""
          }
        },
        {
          "id": "rooms",
          "type": "collections",
          "hidden": false,
          "settings": {
            "title": "לפי חדר",
            "subtitle": ""
          }
        },
        {
          "id": "featured",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "מומלצים",
            "collection": "",
            "limit": 8,
            "buttonLabel": "לכל הרהיטים"
          }
        },
        {
          "id": "delivery",
          "type": "imageText",
          "hidden": false,
          "settings": {
            "title": "משלוח והרכבה",
            "text": "כל מה שצריך לדעת על המשלוח, על ההרכבה ועל ההגעה לבית — בעמוד אחד.",
            "image": "",
            "buttonLabel": "לפרטים",
            "buttonHref": "/pages/delivery-assembly",
            "imageSide": "start"
          }
        },
        {
          "id": "steps",
          "type": "steps",
          "hidden": false,
          "settings": {
            "title": "איך זה עובד",
            "items": [
              {
                "title": "בוחרים",
                "text": "רהיט, מידה וצבע מהקטלוג."
              },
              {
                "title": "מתאמים",
                "text": "קובעים יחד מועד למשלוח."
              },
              {
                "title": "מקבלים",
                "text": "הרהיט מגיע הביתה."
              }
            ]
          }
        },
        {
          "id": "faq",
          "type": "faq",
          "hidden": false,
          "settings": {
            "title": "שאלות נפוצות",
            "items": [
              {
                "q": "אפשר לראות את הרהיט לפני שקונים?",
                "a": "כתבו לנו ונתאם — ונשלח גם תמונות ומידות."
              },
              {
                "q": "איך יודעים שהרהיט ייכנס?",
                "a": "בכל מוצר כתובות המידות. כדאי למדוד גם את הדלתות ואת המעלית."
              }
            ]
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "צריכים עזרה בבחירה?",
            "text": "ספרו לנו על החדר, ונעזור למצוא את מה שמתאים."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "סלון",
          "href": "/collections/living-room"
        },
        {
          "label": "חדר שינה",
          "href": "/collections/bedroom"
        },
        {
          "label": "פינת אוכל",
          "href": "/collections/dining"
        },
        {
          "label": "משרד",
          "href": "/collections/office"
        },
        {
          "label": "תאורה",
          "href": "/collections/lighting"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "משלוח והרכבה",
          "href": "/pages/delivery-assembly"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "משלוחים",
          "href": "/policies/shipping"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "living-room",
        "title": "סלון",
        "description": "ספות, שולחנות ועוד לסלון.",
        "tags": [
          "סלון"
        ]
      },
      {
        "slug": "bedroom",
        "title": "חדר שינה",
        "description": "מיטות, שידות וארונות.",
        "tags": [
          "חדר שינה"
        ]
      },
      {
        "slug": "dining",
        "title": "פינת אוכל",
        "description": "שולחנות וכיסאות לפינת האוכל.",
        "tags": [
          "פינת אוכל"
        ]
      },
      {
        "slug": "office",
        "title": "משרד",
        "description": "שולחנות עבודה, כיסאות ואחסון.",
        "tags": [
          "משרד"
        ]
      },
      {
        "slug": "lighting",
        "title": "תאורה",
        "description": "מנורות וגופי תאורה.",
        "tags": [
          "תאורה"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## מי אנחנו\n\n[איך {{name}} התחילה, ומה מיוחד ברהיטים שלכם.]"
      },
      {
        "slug": "delivery-assembly",
        "title": "משלוח והרכבה",
        "body": "## משלוח\n\n[לאילו אזורים, כמה זמן לוקח, ואיך מתאמים מועד.]\n\n## הרכבה\n\n[האם ההרכבה כלולה, כמה היא עולה, ומי מרכיב.]\n\n## לפני שהמשלוח מגיע\n\n- למדוד את הדלתות, המעלית והמדרגות.\n- לפנות את המקום שבו הרהיט יעמוד."
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## נשמח לעזור\n\nשאלה על רהיט, על מידות או על משלוח — כתבו לנו בוואטסאפ, התקשרו או שלחו מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר."
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## איך יודעים שהרהיט ייכנס?\n\nבכל מוצר כתובות המידות. כדאי למדוד גם את הדלתות ואת המעלית.\n\n## ההרכבה כלולה?\n\n[פרטי ההרכבה — ראו גם את עמוד המשלוח וההרכבה.]"
      }
    ],
    "policies": {
      "shipping": {
        "append": "## הרכבה\n\n[האם ההרכבה כלולה, כמה היא עולה, ומתי מתאמים אותה.]"
      }
    }
  },
  {
    "id": "general",
    "name": "כללי",
    "description": "אתר נקי שמתאים לכל עסק: פתיח, מוצרים, קטגוריות, אודות ושאלות נפוצות.",
    "order": 99,
    "keywords": [],
    "seoDescription": "{{name}} — כל המוצרים במקום אחד, עם דרך קלה ליצור קשר.",
    "theme": {
      "colors": {
        "background": "#fafafa",
        "surface": "#ffffff",
        "text": "#1a1a1a",
        "muted": "#595959",
        "primary": "#1a1a1a",
        "accent": "#2f5d8a",
        "accentSoft": "#e8eef5",
        "border": "#e2e2e2"
      },
      "font": "heebo",
      "art": "plain",
      "radius": "medium",
      "announcement": {
        "enabled": true,
        "text": "ברוכים הבאים ל-{{name}}",
        "href": "/collections/all"
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "{{name}}",
            "title": "כל מה שחיפשתם, במקום אחד",
            "subtitle": "בחרו מוצר, הוסיפו לסל — ואם יש שאלה, אנחנו כאן.",
            "primaryLabel": "לכל המוצרים",
            "primaryHref": "/collections/all",
            "secondaryLabel": "שאלה בוואטסאפ",
            "secondaryHref": "whatsapp",
            "image": ""
          }
        },
        {
          "id": "featured",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "חדש באתר",
            "collection": "",
            "limit": 8,
            "buttonLabel": "לכל המוצרים"
          }
        },
        {
          "id": "collections",
          "type": "collections",
          "hidden": false,
          "settings": {
            "title": "קטגוריות",
            "subtitle": ""
          }
        },
        {
          "id": "about",
          "type": "imageText",
          "hidden": false,
          "settings": {
            "title": "נעים להכיר",
            "text": "כאן כותבים כמה מילים על העסק: מי אתם, מה אתם מוכרים, ולמה כדאי לקנות דווקא אצלכם.",
            "image": "",
            "buttonLabel": "עוד עלינו",
            "buttonHref": "/pages/about",
            "imageSide": "start"
          }
        },
        {
          "id": "faq",
          "type": "faq",
          "hidden": false,
          "settings": {
            "title": "שאלות נפוצות",
            "items": [
              {
                "q": "איך מזמינים?",
                "a": "בוחרים מוצר, מוסיפים לסל ומשלימים את פרטי ההזמנה. אפשר גם לכתוב לנו בוואטסאפ."
              },
              {
                "q": "אפשר לשאול לפני שמזמינים?",
                "a": "בטח. כתבו לנו בוואטסאפ או במייל, ונחזור אליכם."
              }
            ]
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "נדבר?",
            "text": "שאלה על מוצר או על הזמנה — כתבו לנו ונחזור אליכם."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "כל המוצרים",
          "href": "/collections/all"
        },
        {
          "label": "חדש",
          "href": "/collections/new"
        },
        {
          "label": "מבצעים",
          "href": "/collections/sale"
        },
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "משלוחים",
          "href": "/policies/shipping"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "new",
        "title": "חדש",
        "description": "המוצרים החדשים באתר.",
        "tags": [
          "חדש"
        ]
      },
      {
        "slug": "sale",
        "title": "מבצעים",
        "description": "מוצרים במבצע.",
        "tags": [
          "מבצע"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## מי אנחנו\n\nכאן מספרים על {{name}}: איך התחלתם, מה אתם עושים ולמי.\n\n## מה חשוב לנו\n\n- [דבר אחד שחשוב לכם]\n- [ועוד אחד]"
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## נשמח לשמוע מכם\n\nשאלה על מוצר, על הזמנה או על משהו אחר — כתבו לנו בוואטסאפ, התקשרו או שלחו מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר.\n\n## שעות פעילות\n\n[ימים ושעות]"
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## איך מזמינים?\n\nבוחרים מוצר, מוסיפים לסל ומשלימים את פרטי ההזמנה.\n\n## איך משלמים?\n\n[אמצעי התשלום]\n\n## מתי ההזמנה מגיעה?\n\n[זמני אספקה — ראו גם את עמוד המשלוחים]"
      }
    ],
    "policies": {}
  },
  {
    "id": "retail",
    "name": "קמעונאות כללית",
    "description": "לחנות עם הרבה סוגי מוצרים: חדש, מבצעים, מומלצים וקטגוריות.",
    "order": 60,
    "keywords": [
      "חנות",
      "קמעונאות",
      "מתנות",
      "צעצועים",
      "אלקטרוניקה",
      "כלי בית",
      "מכולת",
      "סיטונאות",
      "מוצרי",
      "retail",
      "shop",
      "store"
    ],
    "seoDescription": "{{name}} — חדש, מבצעים ומומלצים, הכל במקום אחד.",
    "theme": {
      "colors": {
        "background": "#ffffff",
        "surface": "#ffffff",
        "text": "#1b1b1b",
        "muted": "#585858",
        "primary": "#1b1b1b",
        "accent": "#b3420d",
        "accentSoft": "#fdf0e8",
        "border": "#e5e5e5"
      },
      "font": "heebo",
      "art": "plain",
      "radius": "small",
      "announcement": {
        "enabled": true,
        "text": "חדש באתר — כל המוצרים במקום אחד",
        "href": "/collections/new"
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "{{name}}",
            "title": "כל מה שצריך, במקום אחד",
            "subtitle": "מוצרים חדשים, מבצעים ומומלצים — מזמינים בקלות, באתר או בוואטסאפ.",
            "primaryLabel": "לכל המוצרים",
            "primaryHref": "/collections/all",
            "secondaryLabel": "למבצעים",
            "secondaryHref": "/collections/sale",
            "image": ""
          }
        },
        {
          "id": "categories",
          "type": "collections",
          "hidden": false,
          "settings": {
            "title": "קטגוריות",
            "subtitle": ""
          }
        },
        {
          "id": "new",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "חדש באתר",
            "collection": "new",
            "limit": 8,
            "buttonLabel": "לכל החדשים"
          }
        },
        {
          "id": "sale",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "מבצעים",
            "collection": "sale",
            "limit": 4,
            "buttonLabel": "לכל המבצעים"
          }
        },
        {
          "id": "recommended",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "מומלצים",
            "collection": "recommended",
            "limit": 4,
            "buttonLabel": "לכל המומלצים"
          }
        },
        {
          "id": "faq",
          "type": "faq",
          "hidden": false,
          "settings": {
            "title": "שאלות נפוצות",
            "items": [
              {
                "q": "איך מזמינים?",
                "a": "בוחרים מוצר, מוסיפים לסל ומשלימים את פרטי ההזמנה."
              },
              {
                "q": "אפשר לשאול לפני שמזמינים?",
                "a": "בטח — כתבו לנו בוואטסאפ או במייל."
              }
            ]
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "יש שאלה?",
            "text": "כתבו לנו ונחזור אליכם."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "כל המוצרים",
          "href": "/collections/all"
        },
        {
          "label": "חדש",
          "href": "/collections/new"
        },
        {
          "label": "מבצעים",
          "href": "/collections/sale"
        },
        {
          "label": "קטגוריות",
          "href": "/collections"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "משלוחים",
          "href": "/policies/shipping"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "new",
        "title": "חדש",
        "description": "המוצרים החדשים באתר.",
        "tags": [
          "חדש"
        ]
      },
      {
        "slug": "sale",
        "title": "מבצעים",
        "description": "מוצרים במבצע.",
        "tags": [
          "מבצע"
        ]
      },
      {
        "slug": "recommended",
        "title": "מומלצים",
        "description": "המוצרים שאנחנו הכי אוהבים.",
        "tags": [
          "מומלץ"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## מי אנחנו\n\n[כמה מילים על {{name}}: ממתי, מה מוכרים, ולמה לקנות דווקא אצלכם.]"
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## נשמח לשמוע מכם\n\nשאלה על מוצר או על הזמנה — כתבו לנו בוואטסאפ, התקשרו או שלחו מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר.\n\n## שעות פעילות\n\n[ימים ושעות]"
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## איך מזמינים?\n\nבוחרים מוצר, מוסיפים לסל ומשלימים את פרטי ההזמנה.\n\n## איך משלמים?\n\n[אמצעי התשלום]\n\n## מתי ההזמנה מגיעה?\n\n[זמני אספקה — ראו גם את עמוד המשלוחים]"
      }
    ],
    "policies": {}
  },
  {
    "id": "services",
    "name": "שירותים",
    "description": "לנותני שירות: מה אתם עושים, איך זה עובד, חבילות ושאלות נפוצות — עם דרך מהירה לפנות.",
    "order": 50,
    "keywords": [
      "שירות",
      "שירותים",
      "ייעוץ",
      "יועץ",
      "יועצת",
      "הדרכה",
      "קורס",
      "סדנה",
      "אימון",
      "מאמן",
      "צילום",
      "צלם",
      "הובלות",
      "שיפוצים",
      "ניקיון",
      "עורך דין",
      "רואה חשבון",
      "services",
      "consulting"
    ],
    "seoDescription": "{{name}} — השירותים, איך זה עובד, ודרך מהירה לפנות אלינו.",
    "theme": {
      "colors": {
        "background": "#f8fafc",
        "surface": "#ffffff",
        "text": "#0f172a",
        "muted": "#475569",
        "primary": "#0f3b66",
        "accent": "#0f766e",
        "accentSoft": "#e6f4f2",
        "border": "#e2e8f0"
      },
      "font": "rubik",
      "art": "plain",
      "radius": "medium",
      "announcement": {
        "enabled": false,
        "text": "",
        "href": ""
      },
      "product": {
        "related": true,
        "whatsapp": true
      },
      "sections": [
        {
          "id": "hero",
          "type": "hero",
          "hidden": false,
          "settings": {
            "eyebrow": "{{name}}",
            "title": "עושים את זה נכון, מהפעם הראשונה",
            "subtitle": "ספרו לנו מה אתם צריכים, ונחזור אליכם עם הצעה ברורה.",
            "primaryLabel": "לתיאום שיחה",
            "primaryHref": "whatsapp",
            "secondaryLabel": "השירותים שלנו",
            "secondaryHref": "/pages/services",
            "image": ""
          }
        },
        {
          "id": "what",
          "type": "imageText",
          "hidden": false,
          "settings": {
            "title": "מה אנחנו עושים",
            "text": "כאן מתארים את השירות: מה אתם עושים, למי, ומה הלקוח מקבל בסוף.",
            "image": "",
            "buttonLabel": "לפירוט השירותים",
            "buttonHref": "/pages/services",
            "imageSide": "start"
          }
        },
        {
          "id": "steps",
          "type": "steps",
          "hidden": false,
          "settings": {
            "title": "איך זה עובד",
            "items": [
              {
                "title": "פונים אלינו",
                "text": "בוואטסאפ, בטלפון או במייל."
              },
              {
                "title": "מתאמים",
                "text": "מבינים יחד מה צריך, ומקבלים הצעה."
              },
              {
                "title": "מתחילים",
                "text": "אחרי האישור שלכם."
              }
            ]
          }
        },
        {
          "id": "packages",
          "type": "products",
          "hidden": false,
          "settings": {
            "title": "חבילות ושירותים",
            "collection": "packages",
            "limit": 6,
            "buttonLabel": "לכל החבילות"
          }
        },
        {
          "id": "faq",
          "type": "faq",
          "hidden": false,
          "settings": {
            "title": "שאלות נפוצות",
            "items": [
              {
                "q": "כמה זה עולה?",
                "a": "זה תלוי במה שצריך. ספרו לנו, ונחזור עם הצעה."
              },
              {
                "q": "תוך כמה זמן אפשר להתחיל?",
                "a": "כתבו לנו, ונבדוק יחד את המועד הקרוב."
              }
            ]
          }
        },
        {
          "id": "contact",
          "type": "contact",
          "hidden": false,
          "settings": {
            "title": "בואו נדבר",
            "text": "שאלה, הצעת מחיר או תיאום — כתבו לנו ונחזור אליכם."
          }
        }
      ]
    },
    "menus": {
      "main": [
        {
          "label": "השירותים",
          "href": "/pages/services"
        },
        {
          "label": "חבילות",
          "href": "/collections/packages"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ],
      "footer": [
        {
          "label": "אודות",
          "href": "/pages/about"
        },
        {
          "label": "השירותים",
          "href": "/pages/services"
        },
        {
          "label": "שאלות נפוצות",
          "href": "/pages/faq"
        },
        {
          "label": "צרו קשר",
          "href": "/pages/contact"
        }
      ]
    },
    "collections": [
      {
        "slug": "packages",
        "title": "חבילות",
        "description": "חבילות ושירותים שאפשר להזמין באתר.",
        "tags": [
          "חבילה"
        ]
      }
    ],
    "pages": [
      {
        "slug": "about",
        "title": "אודות",
        "body": "## מי אנחנו\n\n[מי עומד מאחורי {{name}}, מה הניסיון, ולמה לבחור בכם.]"
      },
      {
        "slug": "services",
        "title": "השירותים שלנו",
        "body": "## [שם השירות]\n\n[מה כולל השירות, למי הוא מתאים ומה מקבלים בסוף.]\n\n## [שם השירות]\n\n[מה כולל השירות, למי הוא מתאים ומה מקבלים בסוף.]"
      },
      {
        "slug": "contact",
        "title": "צרו קשר",
        "body": "## בואו נדבר\n\nשאלה, הצעת מחיר או תיאום — כתבו לנו בוואטסאפ, התקשרו או שלחו מייל. פרטי הקשר מופיעים בתחתית כל עמוד באתר.\n\n## שעות פעילות\n\n[ימים ושעות]"
      },
      {
        "slug": "faq",
        "title": "שאלות נפוצות",
        "body": "## כמה זה עולה?\n\n[איך נקבע המחיר.]\n\n## תוך כמה זמן אפשר להתחיל?\n\n[זמני התחלה.]"
      }
    ],
    "policies": {}
  }
];
